furniture_store/config/routes.rb
Rails.application.routes.draw do
  get 'inventory/all_products'

  get 'inventory/one_product'

  get 'inventory/by_category' => 'inventory#by_category'

  get 'inventory/category/:name' => 'inventory#category', :as => 'category_list'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

furniture_store/app/models/product.rb
class Product < ApplicationRecord
end

furniture_store/app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_products
  	@products = Product.all
  end

  def one_product
  end

  def by_category
  	@categories = Product.select(:category).distinct
  end

  def category
  	@category_name = params[:name]
    @products = Product.where(category: @category_name)
  end

end

furniture_store/app/helpers/inventory_helper.rb
module InventoryHelper
end

furniture_store/app/views/inventory/all_products.html.erb
<h1>Inventory#all_products</h1>

<table border="1">
<tr>
	<th>Name</th>
	<th>Price</th>
	<th>Category</th>
</tr>
<% @products.each do |p| %>
	<tr>
		<td><%= p.name %></td>
		<td>$<%= '%.2f' % p.price %></td>
		<td><%= p.category %></td>
	</tr>
<% end %>
</table>

furniture_store/app/views/inventory/by_category.html.erb
<h1>Inventory Categories</h1>

<table border="1">
<tr>
	<th>Category</th>
	<th>Dynamic Link</th>
</tr>
<% @categories.each do |c| %>
	<tr>
		<td><%= link_to c.category, category_list_path(c.category) %></td>
		<td>"/inventory/category/<%= c.category %>"</td>
	</tr>
<% end %>
</table>

furniture_store/app/views/inventory/category.html.erb
<h1>Inventory for Category <%= @category_name %></h1>

<% if @products.size > 0 %>

	<table border="1">
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Category</th>
	</tr>
	<% @products.each do |p| %>
		<tr>
			<td><%= p.name %></td>
			<td>$<%= '%.2f' % p.price %></td>
			<td><%= p.category %></td>
		</tr>
	<% end %>
	</table>

<% else %>
	
	<p>We're sorry, but we currently have no inventory in our <%= @category_name %> department</p>

<% end %>

furniture_store/app/views/inventory/one_product.html.erb
<h1>Inventory#one_product</h1>
<p>Find me in app/views/inventory/one_product.html.erb</p>