twitter-homage/config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'all_users'		=> 'epicenter#all_users'
  get 'show_user/:id'	=> 'epicenter#show_user', :as => 'show_user'
  get 'following' 		=> 'epicenter#following'
  get 'followers' 		=> 'epicenter#followers'

  get 'stats'			=> 'epicenter#stats'

  get 'now_following'	=> 'epicenter#now_following'

  get 'unfollow'		=> 'epicenter#unfollow'

  get 'tag_tweets'		=> 'epicenter#tag_tweets'

  resources :tweets
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

twitter-homage/app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
    has_many :tweets, through: :tweet_tags
end

twitter-homage/app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	has_many :tweet_tags
    has_many :tags, through: :tweet_tags

    before_validation :link_check, on: :create
	validates :message, presence: true
	validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}
	after_validation :apply_link, on: :create
	
	private

	def link_check
		check = false
		if self.message.include? "http://" 
			check = true
		elsif self.message.include? "https://"
			check = true
		else
			check = false
		end	

		if check == true
			arr = self.message.split
			index = arr.map{ |x| x.include? "http"}.index(true)
			self.link = arr[index]
			if arr[index].length > 23
				arr[index] = "#{arr[index][0..20]}..."	
			end
						
			self.message = arr.join(" ")
		end
    end	

    def apply_link
		arr = self.message.split
		index = arr.map { |x| x.include?("http://") || x.include?("https://") }.index(true)

		if index
			url = arr[index]
			arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
		end

		self.message = arr.join(" ")
	end

end

twitter-homage/app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
end

twitter-homage/app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	
	has_many :tweets

	mount_uploader :avatar, AvatarUploader

    validates :username, presence: true, uniqueness: true

  	serialize :following, Array
  	
end

twitter-homage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :folowing])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

twitter-homage/app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
  	@following_tweets = []

    # Add tweets and follows if the current user is set.
    if current_user
      Tweet.all.each do |tweet|
        if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
          @following_tweets.push(tweet)
        end
      end
      @following_tweets.reverse!
    end
  end

  def show_user
  	@user = User.find(params[:id])
    @following = []
    @followers = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @following.push(user)
      end
    end

    User.all.each do |user|
      if user.following.include?(@user.id)
        @followers.push(user)
      end
    end
  end

  def all_users
    @users = User.order(:name)
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user =  User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end 

  def stats
    @user = current_user
    @following = []
    @followers = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @following.push(user)
      end
    end

    User.all.each do |user|
      if user.following.include?(@user.id)
        @followers.push(user)
      end
    end

  end

  def now_following
    # We are adding the user.id of the user you want to 
    # follow to your following array.
    # and we want to make sure it's saved in there as an integer
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
	  current_user.save

	  redirect_to show_user_path(id: params[:id]) 
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

end

twitter-homage/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

twitter-homage/app/helpers/epicenter_helper.rb
module EpicenterHelper
end

twitter-homage/app/helpers/tweets_helper.rb
module TweetsHelper
    def get_tagged(tweet)
        message_arr = tweet.message.split
        message_arr.each_with_index do |word, index|
            if word[0] == "#"
                if Tag.pluck(:phrase).include?(word)
                    tag = Tag.find_by(phrase: word)
                else
                    tag = Tag.create(phrase: word)
                end
                tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
                message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
            end
        end

        tweet.message = message_arr.join(" ")
        return tweet
    end
end

twitter-homage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterHomage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
          <li><%= link_to "All Users", all_users_path %></li>
          <li><%= link_to "My Stats", stats_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav" %>
                <% end %> 
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
	<div class="container">
    	<%= yield %>
	</div>
</body>

</html>

twitter-homage/app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :message, placeholder: "What's happening?", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.submit "Tweet It!", class: "btn btn-primary" %>
  </div>
<% end %>

twitter-homage/app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

twitter-homage/app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

twitter-homage/app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

twitter-homage/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
    <strong>User:</strong>
    <%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %>
</p>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>